### ISSUE TITLE
Log4j2 jars aren't added to the build artifact

### ISSUE THREAD

**Issue by sergey-melnychuk** [sergey-melnychuk/distributed-algorithms#3]
```
$ java -cp build/libs/distributed-algorithms.jar edu.membership.RemoteNode 10000
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at edu.membership.impl.GossipMembership.<clinit>(GossipMembership.java:12)
	at edu.common.impl.NodeImpl.<init>(NodeImpl.java:24)
	at edu.membership.RemoteNode.run(RemoteNode.java:23)
	at edu.membership.RemoteNode.main(RemoteNode.java:56)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
```

**Comment by sergey-melnychuk** [comment]
Fixed in #5
